beginner_source/colab.rst 첫 문단 번역
hyoyoung/ex-tutorials-kr-2023 pull request #12
Opened 2023-07-22 08:54 UTC by jenner9212

colab.rst 첫 문단 번역

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #9 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
beginner_source/colab.rst 첫 문단 번역하였습니다.

2023-07-23 06:09 UTC, chanmuzi commented
공개된 자료와 동일하게 수정하신 것 같네요..! 그래서 특별히 건드릴 부분은 없어 보입니다

2023-07-23 06:21 UTC, jenner9212 commented
> 공개된 자료와 동일하게 수정하신 것 같네요..! 그래서 특별히 건드릴 부분은 없어 보입니다

공개된 자료와 동일하군요.. 안봐서 몰랐네요 ㅠㅠ

2023-07-23 11:42 UTC, Ssunbell commented
"종속성" 을 개발자들이 사용하는 용어라는 것을 반영해서 "의존성"으로 바꾸면 좋을거 같습니다

2023-07-24 00:27 UTC, hyoyoung requested changes
전반적으로 잘되어있고 사소한 수정이 필요합니다. 확인 부탁드립니다

2023-07-24 00:27 UTC, hyoyoung commented on beginner_source/colab.rst
> +Google Colab에서 튜토리얼을 실행할 때, 튜토리얼이 제대로 작동하려면 충족해야 하는 추가 요구 사항과
'충족'은 '필요한'으로 바꿔쓰면 조금 더 자연스러울거 같습니다

2023-07-24 00:27 UTC, hyoyoung commented on beginner_source/colab.rst
> +Google Colab의 PyTorch 버전
위에서 PyTorch를 파이토치라고 하였는데, 소제목에서는 PyTorch로 번역이 안되어있습니다
파이토치로 통일하는게 좋을거 같습니다

2023-07-29 06:10 UTC, jenner9212 commented on beginner_source/colab.rst
> +Google Colab에서 튜토리얼을 실행할 때, 튜토리얼이 제대로 작동하려면 충족해야 하는 추가 요구 사항과
수정했습니다!

2023-07-29 06:10 UTC, jenner9212 commented on beginner_source/colab.rst
> +Google Colab의 PyTorch 버전
수정했습니다!

2023-07-30 12:25 UTC, merged