advanced_source/cpp_autograd.rst 번역
hyoyoung/ex-tutorials-kr-2023 pull request #14
Opened 2023-07-22 13:18 UTC by 0seob

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #13 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
advanced_source/cpp_autograd.rst 첫 문단을 번역하였습니다.

2023-07-23 03:31 UTC, ganghe74 approved these changes
문제 없는 것 같습니다.

2023-07-23 03:31 UTC, ganghe74 commented on advanced_source/cpp_autograd.rst
> +(`이 튜토리얼 <https://tutorials.pytorch.kr/beginner/blitz/autograd_tutorial.html>`_ 에서 채택되었습니다.)
링크 뒤 #이 빠진 것은, 영어 원문 튜토리얼에서도 유효하지 않은? 링크를 참조하고 있기 때문에 적절한 선택인 것 같습니다.

2023-07-24 00:31 UTC, hyoyoung requested changes
전반적으로 잘되어있고 사소한 수정이 필요합니다. 확인부탁드립니다.

2023-07-24 00:31 UTC, hyoyoung commented on advanced_source/cpp_autograd.rst
> +(`이 튜토리얼 <https://tutorials.pytorch.kr/beginner/blitz/autograd_tutorial.html>`_ 에서 채택되었습니다.)
영어 튜토리얼에서 유효하지 않은 링크를 발견하셨을 경우, 영어 튜토리얼로 PR 보내시는걸 고려해주세요

2023-07-24 00:31 UTC, hyoyoung commented on advanced_source/cpp_autograd.rst
>  ========================
===는 소제목을 표시하는데, 윗 문장의 길이보다 같거나 커야합니다 = 갯수를 늘려주세요

2023-07-24 00:31 UTC, hyoyoung commented on advanced_source/cpp_autograd.rst
> +``Autograd`` 패키지는 유연하고 동적인 신경망을 구축하는데 중요합니다.
> ``Autograd`` 패키지는 유연하고 동적인 신경망을 구축하는데 중요합니다

파이토치 부분이 빠진거 같습니다
PyTorch의 ``Autograd`` 패키지는 유연하고 동적인 신경망을 구축하는데 중요합니다
정도로 수정하면 어떨까요?

2023-07-30 10:08 UTC, 0seob commented on advanced_source/cpp_autograd.rst
> +``Autograd`` 패키지는 유연하고 동적인 신경망을 구축하는데 중요합니다.
수정했습니다.

2023-07-30 10:08 UTC, 0seob commented on advanced_source/cpp_autograd.rst
>  ========================
수정했습니다.

2023-07-30 10:10 UTC, 0seob commented on advanced_source/cpp_autograd.rst
> +(`이 튜토리얼 <https://tutorials.pytorch.kr/beginner/blitz/autograd_tutorial.html>`_ 에서 채택되었습니다.)
영어 원문 튜토리얼은 유효한 링크이나 한국어 튜토리얼에서는 #이후의 링크를 찾을 수 없어 맞는 페이지로 변경하였습니다. 유효하지 않은 링크가 무엇인지 알려주신다면 살펴보겠습니다.

2023-07-30 12:26 UTC, merged