pipeline_tutorial.py 번역
hyoyoung/ex-tutorials-kr-2023 pull request #15
Opened 2023-07-22 14:39 UTC by convin305

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #5 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
pipeline_tutorial의 첫 부분을 번역하였습니다.

2023-07-22 17:56 UTC, jiho3004 commented
8번 라인에서 '거대한 트랜스포머모델을' -> '거대한 트랜스포머 모델을' 띄어쓰기 하면 좋을 것 같습니다.

2023-07-22 18:03 UTC, jiho3004 reviewed
8번 라인에서 '거대한 트랜스포머모델을' -> '거대한 트랜스포머 모델을' 띄어쓰기 하면 좋을 것 같습니다.

2023-07-22 18:04 UTC, jiho3004 commented on intermediate_source/pipeline_tutorial.py
> +거대한 트랜스포머모델을 학습하는 학습하는 방법에 대해서 설명합니다.
```suggestion
거대한 트랜스포머 모델을 학습하는 학습하는 방법에 대해서 설명합니다.
```

2023-07-22 18:05 UTC, jiho3004 commented on intermediate_source/pipeline_tutorial.py
> +거대한 트랜스포머모델을 학습하는 학습하는 방법에 대해서 설명합니다.
8번 라인에서 '거대한 트랜스포머모델을' -> '거대한 트랜스포머 모델을' 띄어쓰기 하면 좋을 것 같습니다.

2023-07-24 00:38 UTC, hyoyoung requested changes
전반적으로 잘되어있습니다. 다른 분들 피드백 확인부탁드립니다.

2023-07-24 00:38 UTC, hyoyoung commented on intermediate_source/pipeline_tutorial.py
> +이전 모델에서 규모를 증가시켰습니다.
same model이면 '이전 모델'도 의미가 통하긴 하지만
'같은 모델'로 하는게 더 자연스럽지 않을까요?

아래 문장 구조가 복잡하여 까다롭긴한데,
> scales up the same model to demonstrate how pipeline parallelism can be
> used to train Transformer models.

같은 모델의 규모를 키워서,
트랜스포머 모델이 파이프라인 병렬화를 이용하여 학습시킬수 있음을 보여줍니다.

정도로 바꿔보면 어떨까요?

2023-07-27 17:08 UTC, convin305 commented on intermediate_source/pipeline_tutorial.py
> +이전 모델에서 규모를 증가시켰습니다.
지호님께서 말씀해주신 띄어쓰기, 멘토님께서 말씀해주신 문장 수정해보았습니다. 감사합니다.

2023-07-30 12:27 UTC, merged