[DOCS] Intermediate_source/seq2seq_translation_tutorial.py 번역 진행
hyoyoung/ex-tutorials-kr-2023 pull request #2
Opened 2023-07-20 13:15 UTC by falconlee236

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #1 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
첫번째 과제인 한 문단 번역하기를 수행했습니다.
C조가 맡은 intermediate_source 폴더에서 
제가 맡은 부분인 seq2seq_translation_tutorial.py에 있는 주석의 첫번째 문단, 두번째 문단을 번역했습니다.

2023-07-20 13:16 UTC, falconlee236 commented
커밋이 더러운 이유는 실수로 .idea를 수정 안하고 커밋 해버려서 고치느라 그랬습니다...

2023-07-22 18:02 UTC, jiho3004 reviewed
9번 라인에 '알 수 있을 것 입니다.' -> '알 수 있을 것입니다.' 띄어쓰기 수정하면 좋을 것 같습니다.

2023-07-23 03:55 UTC, falconlee236 commented
> 9번 라인에 '알 수 있을 것 입니다.' -> '알 수 있을 것입니다.' 띄어쓰기 수정하면 좋을 것 같습니다.

수정 완료했습니다!! 피드백 감사합니다.

2023-07-24 00:12 UTC, hyoyoung requested changes
1. 커밋은 프로젝트마다 다르게 관리하나 보통은 squash merge하는 곳이면 복잡해도 상관없습니다. 다만 커밋을 묶어서 PR을 보낼때는 관리가 조금 필요합니다. 해당 PR의 경우 번역과 상관없은 .gitignore를 업데이트 했기때문에, 별도의 PR분리가 필요합니다. 기본적으로 1개 PR은 1개 의미를 가진다고 보시면 됩니다.
ex) 번역 PR일 경우 번역 1개만. 다른 문법 교정이나, 수정의 경우 별도 PR로 분리

2. 이 부분은
> In this project we will be teaching a neural network to translate from
French to English.

이번 프로젝트에서는 프랑스어에서 영어로 번역을 하는 신경망을 가르쳐보도록 하겠습니다.
정도가 더 자연스럽지 않을까요?

2023-07-24 11:09 UTC, falconlee236 commented
1번 사항은 .gitignore을 revert한 커밋으로 해결 완료 했습니다.
하나의 pull request에는 하나의 전체적인 내용만을 담도록 하겠습니다.

2번 사항은 추가적인 commit을 통해서 수정 완료했습니다.!

2023-07-27 14:35 UTC, hyoyoung approved these changes
looks good to me

2023-07-30 12:23 UTC, merged