torchvision_tutorial.rst translation
hyoyoung/ex-tutorials-kr-2023 pull request #23
Opened 2023-07-23 05:32 UTC by ChoHyoungSeo

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- 이슈번호 : #22

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

2023-07-23 11:01 UTC, falconlee236 commented
번역 잘 하신것 같습니다!! 고생 많으셨습니다.

2023-07-24 15:13 UTC, hyoyoung requested changes
전반적으로 잘되어있고 사소한 수정이 필요할거 같습니다 확인 부탁드립니다

2023-07-24 15:13 UTC, hyoyoung commented on intermediate_source/torchvision_tutorial.rst
> +위 데이터셋은 170장의 이미지와 345명의 보행자 인스턴스로 이루어져 있으며 사용자 정의 데이터셋을 활용하여
instances of pedestrians는 보행자 인스턴스보다는
보행자 사례 정도로 순화해보는건 어떨까요?

2023-07-24 15:13 UTC, hyoyoung commented on intermediate_source/torchvision_tutorial.rst
> +인스턴스 분할(Instance Segmentation)을 학습하기 위해 torchvision에서의 새로운 기능들을 사용하는 방법에 관해서 설명할 것입니다.
위와 아래 문장이 하나인데, 너무 길면 2개로 분할하는것도 가독성에 좋을거 같습니다

2023-07-29 09:06 UTC, ChoHyoungSeo commented on intermediate_source/torchvision_tutorial.rst
> +인스턴스 분할(Instance Segmentation)을 학습하기 위해 torchvision에서의 새로운 기능들을 사용하는 방법에 관해서 설명할 것입니다.
네, 코멘트 주셔서 감사합니다. 문장을 나누어 수정하도록 하겠습니다!

2023-07-29 13:01 UTC, ChoHyoungSeo commented on intermediate_source/torchvision_tutorial.rst
> +위 데이터셋은 170장의 이미지와 345명의 보행자 인스턴스로 이루어져 있으며 사용자 정의 데이터셋을 활용하여
네, 피드백 주셔서 감사합니다. 혹시 translation guide (https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md) 용어 규칙에는 instance를 인스턴스로 번역한다는 내용이 있었는데, 
꼭 따르지 않아도 괜찮은 것인지 질문 드립니다~!

2023-07-29 13:14 UTC, ChoHyoungSeo commented
피드백 반영하여 수정했습니다. 감사합니다.

2023-07-31 15:35 UTC, hyoyoung requested changes

2023-07-31 15:35 UTC, hyoyoung commented on intermediate_source/torchvision_tutorial.rst
> +TorchVision 객체 검출 미세조정(Finetuning) 튜토리얼
위의 ===는 해당 문서의 소제목입니다. 지우면 안됩니다

2023-08-01 10:43 UTC, ChoHyoungSeo commented on intermediate_source/torchvision_tutorial.rst
> +TorchVision 객체 검출 미세조정(Finetuning) 튜토리얼
네, 알겠습니다. 수정하도록 하겠습니다! 피드백 주셔서 감사합니다!

2023-08-01 13:45 UTC, ChoHyoungSeo commented
소제목 부분 수정했습니다!
피드백 주셔서 감사합니다!!

2023-08-01 15:21 UTC, hyoyoung approved these changes
good

2023-08-01 15:21 UTC, merged