char_rnn_generation_tutorial 번역
hyoyoung/ex-tutorials-kr-2023 pull request #24
Opened 2023-07-23 06:28 UTC by kimgyujin

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #20 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
char_rnn_generation_tutorial의 원문 일부분이 한국어로 번역이 됩니다.

2023-07-23 11:23 UTC, falconlee236 commented
번역 잘 읽었습니다!!! 고생 많았습니다.

2023-07-24 15:15 UTC, hyoyoung requested changes
전반적으로 잘되어있고, 사소한 수정이 필요합니다. 확인부탁드립니다.

2023-07-24 15:15 UTC, hyoyoung commented on intermediate_source/char_rnn_generation_tutorial.py
> +`1번째 튜토리얼 </intermediate/char_rnn_classification_tutorial>`에서 이름들을 언어로 분류하기 위해 RNN을 사용했습니다.
영어에서는 단수,복수를 구분해서 쓰지만,
한국어에서는 강조 의미가 아니면 복수를 제외하는 것도 가독성에 좋습니다
'이름들'보다는 '이름'으로 바꿔보는건 어떨까요

2023-07-29 04:51 UTC, kimgyujin commented on intermediate_source/char_rnn_generation_tutorial.py
> +`1번째 튜토리얼 </intermediate/char_rnn_classification_tutorial>`에서 이름들을 언어로 분류하기 위해 RNN을 사용했습니다.
그렇군요... 코멘트 감사합니다. 수정하겠습니다!

2023-07-31 15:36 UTC, merged