flask_rest_api_tutorial 번역
hyoyoung/ex-tutorials-kr-2023 pull request #25
Opened 2023-07-23 08:16 UTC by diligejy

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(숫자)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

2023-07-23 10:33 UTC, convin305 commented on intermediate_source/flask_rest_api_tutorial.py
> +# 다음 섹션에서는 추론 코드 작성을 중점을 해보겠습니다.
다음 섹션에서는 추론 코드 작성을 중점으로 해보겠습니다. 
이렇게 하면 더 좋을 것 같습니다!

2023-07-23 11:29 UTC, falconlee236 commented
번역 고생 많으셨습니다!!!

2023-07-24 15:23 UTC, hyoyoung requested changes
긴 문서를 번역하느라 고생하셨습니다
전반적으로 잘되어있고, 사소한 수정이 필요합니다.
확인부탁드립니다

2023-07-24 15:23 UTC, hyoyoung commented on intermediate_source/flask_rest_api_tutorial.py
> +# 이 엔드포인트는 HTTP POST 방식으로 이미지를 포함하는 file 매개변수를 요청합니다.
file에도 ``가 필요할거 같습니다.

2023-07-24 15:23 UTC, hyoyoung commented on intermediate_source/flask_rest_api_tutorial.py
>  # ------------
---는 소제목입니다 글자가 늘어나면 그 숫자에 맞게 --- 숫자도 늘어나야합니다

2023-07-24 15:23 UTC, hyoyoung commented on intermediate_source/flask_rest_api_tutorial.py
> +# 요청(requests):
위에 요청(requests)로 병기한 부분이 있기때문에, 두번째부터는 요청만 쓰셔도 될거 같습니다

2023-07-24 15:23 UTC, hyoyoung commented on intermediate_source/flask_rest_api_tutorial.py
> +#    모델 로드는 메모리 및 컴퓨팅 측면에서 비용이 많이 드는 작업일 수 있습니다.
로드(load)는 그대로도 많이 쓰이나, 여기서는 읽어들인다로 순화해도 좋을거 같습니다
모델 읽어들이기는 메모리 및 컴퓨팅 측면에서 비용이 많이 드는 작업일 수 있습니다.

2023-07-24 15:23 UTC, hyoyoung commented on intermediate_source/flask_rest_api_tutorial.py
> +#   모델이 이미지에서 아무것도 인식하지 못하는 경우를 처리하도록 구현을 향상시킵니다.
enhance는 여기서는 고도화하다로 바꾸거나 구현을 개선합니다 정도로 바꾸는건 어떨까요?

2023-07-30 07:33 UTC, diligejy commented on intermediate_source/flask_rest_api_tutorial.py
> +# 다음 섹션에서는 추론 코드 작성을 중점을 해보겠습니다.
코멘트 감사합니다!

2023-07-30 07:35 UTC, diligejy commented
> 번역 고생 많으셨습니다!!!

감사합니다.

2023-07-30 07:36 UTC, diligejy commented on intermediate_source/flask_rest_api_tutorial.py
>  # ------------
아 그렇군요 알려주셔서 감사합니다

2023-07-30 07:37 UTC, diligejy commented on intermediate_source/flask_rest_api_tutorial.py
> +#    모델 로드는 메모리 및 컴퓨팅 측면에서 비용이 많이 드는 작업일 수 있습니다.
넵!

2023-07-30 07:38 UTC, diligejy commented on intermediate_source/flask_rest_api_tutorial.py
> +#   모델이 이미지에서 아무것도 인식하지 못하는 경우를 처리하도록 구현을 향상시킵니다.
동의합니다 감사합니다!

2023-07-30 07:43 UTC, diligejy commented on intermediate_source/flask_rest_api_tutorial.py
> +# 이 엔드포인트는 HTTP POST 방식으로 이미지를 포함하는 file 매개변수를 요청합니다.
넵~~

2023-07-31 15:37 UTC, hyoyoung approved these changes
good

2023-07-31 15:37 UTC, merged