advanced_source/cpp_frontend.rst 첫 문단 번역
hyoyoung/ex-tutorials-kr-2023 pull request #7
Opened 2023-07-22 07:17 UTC by ganghe74

이 커밋은 연습용 repository인 ex-tutorials-kr-2023 저장소 대상 커밋입니다.

collection => 컬렉션
위 단어의 번역은 http://www.ktword.co.kr/ 를 참고하였습니다.

ref: https://github.com/hyoyoung/ex-tutorials-kr-2023/issues/6

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #6 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

커밋 내용대로, advanced_source/cpp_frontend.rst의 첫 문단을 번역하였습니다.

리뷰 부탁드립니다.

2023-07-22 13:25 UTC, 0seob approved these changes
4번 줄에서 '프레임워크닝 대한' -> '프레임워크에 대한' 오타 있습니다.

나머지는 좋아 보여요!!

2023-07-23 03:13 UTC, ganghe74 commented
리뷰 감사합니다, 오타 수정 완료했습니다.

2023-07-24 00:22 UTC, hyoyoung requested changes
전반적으로 잘되어있고 사소한 수정이 필요합니다. 확인 부탁드립니다.

2023-07-24 00:22 UTC, hyoyoung commented on advanced_source/cpp_frontend.rst
> +정의하고 불러올 수 있는 API와 병렬 데이터로더; 직렬화 루틴 등...
한국어에서는 ;를 기본적으로 사용하지 않습니다. 강조의 의미가 아니면 제외하여 주시기 바랍니다
https://korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=242976&pageIndex=1

또한 영문에서는 마지막 문장의 끝이 .로 끝나있는데, 번역본에서는 ...로 바뀌어있습니다.
강조나 특별한 의미가 있지 않으면 원본 문장 구조를 유지 부탁드립니다.

2023-07-24 00:23 UTC, hyoyoung commented
이건 그냥 제안인데, built-in은 '내장'으로 바꾸는건 어떨까요?
그대로 두셔도 되는데 내장 컬렉션으로도 많이 쓰이는거 같습니다.

2023-07-24 02:41 UTC, khleevx commented
@hyoyoung 
피드백 감사합니다.

1. built-in은 처음에만 "내장(built-in)" 으로 영어 표현을 언급하고, 이후로 "내장" 으로 번역하는 형태로 개선했습니다.
2. 리뷰 반영하여 세미콜론 들어간 부분을 "예를 들어, A, B, C 등이 있습니다." 형태로 개선했습니다.

2023-07-24 02:42 UTC, khleevx commented
빌드도 문제없이 된 것 확인했습니다.
더 이상 문제 없으면 마스터 브랜치에 병합 부탁드립니다 !

<img width="656" alt="chrome_MxK6LSTS6u" src="https://github.com/hyoyoung/ex-tutorials-kr-2023/assets/30896956/7f976d54-a167-4572-9433-b309e41eacb2">

2023-07-27 14:36 UTC, hyoyoung approved these changes
looks good to me

2023-07-27 14:37 UTC, merged